name: Build Game Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: List files for debug
        run: dir /s /b
        shell: cmd

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Game.sln

      - name: Build solution
        run: msbuild Game.sln /p:Configuration=Release /p:IncludePath="$(pwd)\SFML\SFML-2.5.1\include" /m